### ISSUE TITLE
可乐的工位

### ISSUE THREAD

**Issue by kele59** [zaxlct/python-django-learning#5]
![img_0832](https://user-images.githubusercontent.com/14342431/34923736-902fc41e-f9d9-11e7-9c64-cf63254299e1.jpg)
**现拍，现发。。没有整理**

**Comment by kele59** [comment]
我们是在小区里租了一个三室两厅作为办公地点。所以看起来好像是在家里，其实是工位。    
右边是我的 Mac ，左边公司配置的显示屏太垃圾了，极少使用，
Mac  下是一个很大的鼠标垫，画面是大雄和哆啦A梦。。。

**Comment by kele59** [comment]
鼠标垫左侧是《ES6标准入门第三版》，工具书，随时翻看查阅。
书后面是今天的早餐——面包。
书左边是水杯和茶叶（蒲公英根）。
水杯左边的书是《编码》



东西不多，有点小乱。这就是我的工位。

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
